Repository wecode-bootcamp-korea/39-1st-WCF-frontend, pull requests merged in 2022-11, with the labels that each got.

#3 [ADD & MODIFIED] : 공통부분 스타일 수정 & src-images 폴더 추가
  src/images/icon/star-spripe.png
  src/styles/common.scss
  src/styles/variables.scss
Labels: 도움 요청, 멘토 리뷰 요청

#4 [39기 정효원] Modify: Footer 수정 사항 반영 완료
  public/images/footer/footer-instagram.png
  public/images/footer/footer-youtube.png
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청, 수정 요청

#5 [39기 정효원] Modify: Nav 수정 요청 사항 반영 완료 / subCategory Link 경로 추가
  public/images/nav/cart.png
  public/images/nav/heart.png
  public/images/nav/magnify-glass.png
  src/components/Nav/MainCtgData.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/components/Nav/SpecialCtgData.js
  src/pages/Main/Main.js
Labels: 완료

#13 [39기 정효원] Modify: Nav 바 상품리스트에 id값 전달 및 Token에 따른 로그인/로그아웃 처리 추가
  src/Router.js
  src/components/Nav/MainCtgData.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#6 [39기 구수정] Modify: 마이너 리뷰 해결
  README.md
  public/data/productListData.json
  public/images/icons/gez-xavier-mansfield-b34E1vh1tYU-unsplash.jpg
  public/images/icons/marcel-strauss-hwLiTFTGJCY-unsplash.jpg
  public/index.html
  src/Router.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.scss
  src/pages/ProductList/Brand/Brand.js
  src/pages/ProductList/Brand/Brand.scss
  src/pages/ProductList/Price/Price.js
  src/pages/ProductList/Price/Price.scss
  src/pages/ProductList/Product/Product.js
  src/pages/ProductList/Product/Product.scss
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/Size/Size.js
  src/pages/ProductList/Size/Size.scss
Labels: 멘토 리뷰 요청

#14 [39기 정효원] Modify: Nav 바 카테고리 id 값 겹치는 에러 수정 완료
  src/components/Nav/MainCtgData.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
Labels: 멘토 리뷰 요청

#8 [39기 박문영] Add: 상품 상세 페이지 기능구현
  README.md
  public/data/productDetailMockData.json
  public/images/productdetail/products-title.jpg
  public/images/productdetail/sample-img.jpg
  public/images/productdetail/t-shirts-1.jpg
  src/Router.js
  src/images/icon/btn-sprite.png
  src/images/icon/heart-stripe.png
  src/images/icon/plus-minus-stripe.png
  src/images/icon/sns-icons.png
  src/images/productdetail/banner-1.jpg
  src/pages/ProductDetail/CartConfirm/CartConfirm.js
  src/pages/ProductDetail/CartConfirm/CartConfirm.scss
  src/pages/ProductDetail/ImgArea/ImgArea.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
Labels: 멘토 리뷰 요청

#11 [39기 오주형] Modify: 리뷰 사항 반영
  src/images/icon/signin/term-check.svg
  src/pages/Cart/Cart.scss
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: 수정 요청, 추가 기능 구현 중

#10 [39기 오주형] ADD: 장바구니 선택 상품 통신 후 코드 수정 중
  public/data/CartData.json
  public/data/data.json
  src/images/cart/IMG_8905.JPG
  src/images/cart/bag.png
  src/images/cart/basket-img.png
  src/images/cart/bg-component.png
  src/images/cart/btn-x.svg
  src/images/cart/btn_x_gray.svg
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/components/CartEmpty.js
  src/pages/Cart/components/CartFilled.js
  src/pages/Login/Login.js
Labels: 멘토 리뷰 요청

#9 [39기 박문영] Add : 결제페이지 데이터 적용 중
  public/data/paymentdata.json
  src/Router.js
  src/pages/Payment/Payment.js
  src/pages/Payment/Payment.scss
Labels: 멘토 리뷰 요청
